CONTEXT = 'context'
MESSAGE = 'message'
CATALOG = 'catalog'
BPP_DESCRIPTOR = 'descriptor'
# LOCAVORA CHANGE was bpp/providers
BPP_PROVIDERS = 'providers'
BPP_FULFILLMENTS = 'fulfillments'
BPP_CATEGORIES = 'categories'
BPP_ID = 'bpp_id'
DOMAIN = 'domain'
ITEMS = 'items'
ID = 'id'
DESCRIPTOR = 'descriptor'
LOCATIONS = 'locations'
CATEGORIES = 'categories'
GPS = 'gps'
LOCATION_ID = 'location_id'
CATEGORY_ID = 'category_id'
FULFILLMENT_ID = 'fulfillment_id'
PRICE = 'price'
RATING = 'rating'


#######################
BPP_DETAILS = 'bpp_details'
ITEM_DETAILS = 'item_details'
PROVIDER_DETAILS = 'provider_details'
LOCATION_DETAILS = 'location_details'
CATEGORY_DETAILS = 'category_details'
FULFILLMENT_DETAILS = 'fulfillment_details'

